services:
  backend:
    build:
      context: ./typingx-backend/typingx-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - qldt_net

  mssql: # Đổi tên dịch vụ từ postgres sang mssql
    image: mcr.microsoft.com/mssql/server:2022-latest # Sử dụng image SQL Server
    restart: always
    ports:
      - "1433:1433" # Cổng mặc định của SQL Server
    environment:
      ACCEPT_EULA: "Y" # Bắt buộc phải chấp nhận EULA của Microsoft SQL Server
      SA_PASSWORD: "becamexA@123" # Thay thế bằng mật khẩu mạnh của bạn cho user 'sa'
      MSSQL_PID: "Express" # Chọn phiên bản Developer (miễn phí cho dev/test) hoặc "Express"
    # MSSQL_DB: QLDT # Bạn có thể tạo DB ở đây, hoặc tốt hơn là tạo qua migrations từ ứng dụng
    volumes:
      - ./mssql/backup:/var/backup
      - ./mssql/init/restore.sh:/docker-entrypoint-initdb.d/restore.sh
    # - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql # Không dùng cách này cho SQL Server
    networks:
      - qldt_net

volumes:
  mssql_data:

networks:
  qldt_net:
    driver: bridge
